### ISSUE TITLE
email sended with sgml mime type

### ISSUE THREAD

**Issue by besstiolle** [groupe-sii/ogham#41]
> Mime Type detection policy
> 
> When you send an email, it is really important to indicate what is the type of the message (html, text or maybe anything else). The library automatically detects for you the Mime Type of the email content and add this information into the real sent email.

In version 1.0.1-SNAPSHOT we've got some problem to send email. Some of them (but not all ?) are sended with type mime sgml.

It seems to be linked to this bugs https://github.com/arimus/jmimemagic/issues/27 but we've got no idea to fix it.

And without new release https://mvnrepository.com/artifact/fr.sii.ogham/ogham-core ... it's hard to find a solution. :)

Thank you buddy :)

**Comment by aurelien-baudet** [comment]
JMimeMagic is no more supported so I replaced it by Apache Tika
