### ISSUE TITLE
Please do not use start.spring.io for your integration tests

### ISSUE THREAD

**Issue by snicoll** [groupe-sii/ogham#49]
I am working on the Spring Initializr project that powers start.spring.io and we have noticed some increased traffic yesterday that traces back to your project. Are you using [the production instance](https://github.com/groupe-sii/ogham/blob/master/ogham-test-classpath/src/main/java/fr/sii/ogham/test/classpath/springboot/SpringStarterInitializer.java#L33) as an asset in your integration tests by any chance?

If you are, we'd like you to consider other options because it distorts our metrics which are meant to understand better how the instance is used by actual users. We have also traced the logs and found more than 10K projects generated on May 22 that have similar characteristics from a single IP address, which we suspect is yours.

We haven't configured a rate limiting API on start.spring.io as there are a lot (really a lot) of users out there and any form of rate limiting based on the IP may actually prevent legitimate users to create a project. Rather we count on the community to use the instance responsibly.

There are a couple of much better solutions than relying on an external network call as part of your tests:

* Start your own instance locally. It's actually very easy and is described [in detail in the documentation](http://docs.spring.io/initializr/docs/current-SNAPSHOT/reference/html/create-instance.html)
* Use [wiremock with stubs that we provide](http://docs.spring.io/initializr/docs/current-SNAPSHOT/reference/html/_using_the_stubs.html) to simulate a response from the service. It won't match the request that you're making for sure but we can improve the stubs if necessary

Let me know if you have any question about this.

**Comment by aurelien-baudet** [comment]
Hello,

I tried to avoid requesting start.spring.io too many times by adding a cache on Travis CI. However, it seems that it doesn't work in all cases. Sorry for the disturbance.

I didn't know that the initializer project was available. I will use it as it does exactly what I need.

Thank you and sorry again.

**Comment by snicoll** [comment]
@aurelien-baudet you closed the issue but I can't see any link to a commit that would answer our concern. Can you please clarify? (I've found something for  #50 looking at the commits though)

**Comment by aurelien-baudet** [comment]
@snicoll 

I added the User-Agent :
`		RequestEntity<Void> request = RequestEntity.get(expanded)
										.header(USER_AGENT, "ogham/"+oghamProperties.getOghamVersion())
										.build();
`

However the change that you are really interested in is :
`
		String url = springStarterProperties.getUrl()
`

This property is set to a custom server that uses Spring Intializr web (using custom metadata). That way the fix could be done very fasy to avoid spamming your servers. Travis CI now uses the custom server instead of yours

Both are in commit 0ef44a7
