### ISSUE TITLE
Something is trying to load sunrsasign.jar when using MultiTemplateContent (Fedora 25 OpenJDK 8)  

### ISSUE THREAD

**Issue by MaggieLeber** [groupe-sii/ogham#51]
My initial simple explorations trying to use Ogham in a non-Spring environment are hitting a snag; 

When I do `MessagingService.send(new Email)` and the Email contains 
`content(new MultiTemplateContent...` for either Thymeleaf or Freemarker templates, 
_something_ is trying to load 
`file:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.131-1.b12.fc25.x86_64/jre/lib/sunrsasign.jar`
...and I'm having the dickens of a time trying to track down who in this pile of dependencies is doing the call. This jar does not exist any more; the classes it contained have been repackaged in the JDK a while back. 

Anybody have any clues?

**Comment by MaggieLeber** [comment]
Tracked down the problem. My error. Closing.

**Comment by aurelien-baudet** [comment]
Hello,

I have installed a Fedora 25 server 64bits. I installed openjdk 1.8.0.131-1.b12.fc25.x86_64.
I ran the FullSample  (multitemplates with thymeleaf that references external css stylesheets and images) with Ogham v1.1.1sent from GMail (SSL) to yopmail. It works as expected.

Could you provide more information please:

- Which Ogham version are you using ?
- Can you provide a minimal test (Ogham intiialization, Ogham email sending code, templates and template resources) to help me reproduce the issue ?
- Can you provide me the error logs ?

Thank you

**Comment by MaggieLeber** [comment]
I got lost because the example docs don't make clear that `SimpleBean` is obsolete, and has been replaced by classes in `fr.sii.ogham.core.template.context` ...my attempt to implement my own `Context` went awry; the jar loading failure was a total red herring. 

New users will also likely have trouble not knowing that `ogham.email.javamail.authenticator.username` is now `ogham.email.email.authenticator.username`, same for `.password`. 

I'm now looking at the possibility of extending output to `POSTing` a JSON doc to a RESTful web service...should be interesting.

**Comment by aurelien-baudet** [comment]
@MaggieLeber 

You are using the master version that is not currently released. The new documentation is currently available on branch doc/asciidoctor if you want (directly in the README for the moment). It will be  available on master in a few days. I'm using a separate branch because I remove totally the usage of markdown in favor of asciidoctor

**Comment by MaggieLeber** [comment]
Actually I started out using the 1.1.1 Maven artifact thinking it was the latest release; didn't even look at the source until I couldn't get anything to connect to an SMTP server. 

Asciidoctor is indeed superior.  I'll watch the repo...
